config/routes.rb
KwAdministrador::Application.routes.draw do

  resources :user_sessions
  resources :users
  resources :password_resets
  resources :atualizar
  resources :contacts
  namespace(:admin){
    resources :contacts
    resources :static_contents
    resources :users do
      collection do
        get 'search'
      end
    end
    
    root :to => "static_contents#index"
  }
  
  resources :homenew
  resources :portfolio do
    collection do
      get 'adriane'
      get 'aquaclor'
      get 'castelatto'
      get 'fasterm'
      get 'ffa'
      get 'nautilus'
      get 'tegula'
      get 'unilever'
      get 'wellnessfit'
      get 'nesporte'
      get 'clinicasaraiva'
      get 'putzmeister'
      get 'ceusystem'
      get 'giotto'   
    end
  end
  
  root :to => "homenew#index"
  match 'cadastro' => "users#new"
  match 'login' => 'user_sessions#new'  
  match 'logout' => 'user_sessions#destroy'  

end

app/models/user.rb
class User < ActiveRecord::Base
  acts_as_authentic do |c|
    c.login_field = 'email'
  end
  
  acts_as_authorization_subject
  
  scoped_search :on => [:name, :last_name, :email]
  
  validates_presence_of :name, :message=> " - preencha o campo!"
  validates_presence_of :last_name, :message=> " - preencha o campo!"
  validates_presence_of :email, :message=> " - preencha o campo!"
  
  attr_writer :role
  after_save :define_role

  def role
    @role
    if self.has_role? :admin
      @role = :admin
    elsif self.has_role? :supervisor
      @role = :supervisor
    elsif self.has_role? :user
      @role = :user
    end
  end

  def define_role
    if @role
      self.has_no_roles!
      self.has_role! @role
    end
  end

  def deliver_password_reset_instructions!
    reset_perishable_token!
  end
end

app/controllers/admin/users_controller.rb
class Admin::UsersController < ApplicationController
  layout "inadmin"
  
  def index
    @users = User.all.paginate :page => params[:page],:per_page => 20
  end

  def show
    @user = User.find(params[:id])
  end
  
  
  def edit
    @user = User.find(params[:id])
  end

  def update
    @user = User.find(params[:id])
    if @user.update_attributes(params[:user])
      redirect_to admin_user_path(@user), :notice  => "Dados Atualizados com sucesso!"
    else
      render :action => 'edit'
    end
  end
  
  def destroy
    @user = User.find(params[:id])
    @user.destroy
    redirect_to admin_users_path, :notice => "Usuário Deletado com sucesso!"
  end
  
  def search
    if !params[:keyword].blank?
      @Results = User.search_for(params[:keyword]).paginate :page => params[:page],:per_page => 20
    end
  end
    
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_filter :navegadorie6
  layout "admin"
  def new
    @user = User.new
  end

  def create
    @user = User.new(params[:user])
    @user.role = "user"    
    if !@user.save
      @user.errors
    end
  end

  def edit
    @user = current_user
  end

  def update
    @user = current_user
    if @user.update_attributes(params[:user])
      redirect_to home_index_path, :notice  => "Dados Atualizados com sucesso!"
    else
      render :action => 'edit'
    end
  end

end

app/helpers/admin/users_helper.rb
module Admin::UsersHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/_form.html.erb
<%content_for :head do%>
<%= stylesheet_link_tag "cadastro"%>
<%=javascript_include_tag "jquery.validate.min.js"%>
<%=javascript_include_tag "meusmetodos.js"%>
<%#=javascript_include_tag "jquery.meio.mask.js"%>
	<script>
		jQuery(document).ready(function(){		
    	jQuery('#new_user').validate({
        rules: {
            "user[name]": {
                required: true,
                minlength: 2
            },
			"user[last_name]": {
                required: true,
                minlength: 2
            },
			"user[email]": {
                required: true,
                email: true
            },
			"user[password]":{
				required:true,
				minlength: 6
			},			
			"user[password_confirmation]": {
                required: true,
                minlength: 6,
				equalTo: "#user_password"
            }
			
        },
        messages: {
            "user[name]":{
				required: "Preencha o seu nome",
				minlength: 	"Mínimo de 2 caracteres"
			},
			"user[last_name]":{
				required: "Preencha o seu sobrenome",
				minlength: 	"Mínimo de 2 caracteres"
			},
			"user[email]":{
				required: "Preencha o seu email",
				email: "Informe um email válido"	
			},
			"user[password]":{
				required: "Preencha com uma senha",
				minlength: "Mínimo de 6 caracteres"	
			},
			"user[password_confirmation]":{
				required: "Preencha com a confirmação",
				minlength: "Mínimo de 6 caracteres",
				equalTo: "Confirmação não é igual a senha"	
			}
        }
    });
});
	</script>

<% end %>

<div id="flash_error_cadastro" style="display:none;"></div>
<div id="box_registration">
	<%= form_for @user, :remote => true do |f| %>
		<div class="field">
			<%= f.label :name, "Nome" %>
			<%= f.text_field :name %>
		</div>
		<div class="field">
			<%= f.label :last_name, "Sobrenome" %>
			<%= f.text_field :last_name %>
		</div>
		<div class="field">
			<%= f.label :email, "E-mail" %>
			<%= f.text_field :email %>
		</div>
		<div class="field">
			<%= f.label :password, "Senha" %>
			<%= f.text_field :password %>
		</div>
		<div class="field">
			<%= f.label :password_confirmation, "Confirmar Senha" %>
			<%= f.text_field :password_confirmation %>
		</div>
		<div class="actions">
			<%= f.submit "Salvar", :class => "Bt_enviar"  %>
		</div>
	<% end %>
</div>

app/views/users/create.js.erb
<%if !@user.errors.blank?%>
	jQuery('#flash_error_cadastro').addClass('flash_ops');
	jQuery('#flash_error_cadastro').show();
	erro = "";
	erro += "<%= escape_javascript(image_tag("img_ops.png", :id=>"Box_warning_img"))%>";	
	erro += "<div class='Box_warning_text'>";
	erro += "	<h2>Ops!</h2>";
	erro += "	<p>";
	erro += "<%= escape_javascript(raw("Nome "+ @user.errors[:name].to_s + " <br/ >")) if !@user.errors[:name].to_s.blank?%>";
	erro += "<%= escape_javascript(raw("Sobrenome " + @user.errors[:last_name].to_s + "<br/ >")) if !@user.errors[:last_name].empty?%> ";
	erro += "<%= escape_javascript(raw("As senhas não conferem! <br />")) if !@user.errors[:password].empty?%>";
	erro += "<%= escape_javascript(raw("E-mail já cadastrado ou em branco! <br>")) if !@user.errors[:email].empty?%>";
	erro += 	"</p>";
	erro += "<br /><br />"
	erro +=	"</div>";
	erro += "<div class='clear'></div>";
	jQuery('#flash_error_cadastro').html(erro);
<%else%>
	window.location.href = "<%= login_path %>";
<%end%>

app/views/users/edit.html.erb
<% 
	content_for :title do "Cadastrar Usuário" end
%>

<h1>Editar Usuário</h1>
<br />
<%= render 'form' %>

<%#= link_to 'Show', @user %>
<%#= link_to 'Back', users_path %>

app/views/users/new.html.erb
<% 
	content_for :title do "Cadastrar Usuário" end
%>
<h1>Cadastrar Usuário!</h1>
<br />

<%= render 'form' %>

app/views/users/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Name:</b>
  <%= @user.name %>
</p>

<p>
  <b>Last name:</b>
  <%= @user.last_name %>
</p>

<p>
  <b>Email:</b>
  <%= @user.email %>
</p>

<p>
  <b>Crypted password:</b>
  <%= @user.crypted_password %>
</p>

<p>
  <b>Password salt:</b>
  <%= @user.password_salt %>
</p>

<p>
  <b>Persistence token:</b>
  <%= @user.persistence_token %>
</p>

<p>
  <b>Perishable token:</b>
  <%= @user.perishable_token %>
</p>

<p>
  <b>Login count:</b>
  <%= @user.login_count %>
</p>

<p>
  <b>Failed login count:</b>
  <%= @user.failed_login_count %>
</p>

<p>
  <b>Last request at:</b>
  <%= @user.last_request_at %>
</p>

<p>
  <b>Current login at:</b>
  <%= @user.current_login_at %>
</p>

<p>
  <b>Last login at:</b>
  <%= @user.last_login_at %>
</p>

<p>
  <b>Current login ip:</b>
  <%= @user.current_login_ip %>
</p>

<p>
  <b>Last login ip:</b>
  <%= @user.last_login_ip %>
</p>


<%= link_to 'Edit', edit_user_path(@user) %> |
<%= link_to 'Back', users_path %>