config/routes.rb
KwAdministrador::Application.routes.draw do

  resources :user_sessions
  resources :users
  resources :password_resets
  resources :atualizar
  resources :contacts
  namespace(:admin){
    resources :contacts
    resources :static_contents
    resources :users do
      collection do
        get 'search'
      end
    end
    
    root :to => "static_contents#index"
  }
  
  resources :homenew
  resources :portfolio do
    collection do
      get 'adriane'
      get 'aquaclor'
      get 'castelatto'
      get 'fasterm'
      get 'ffa'
      get 'nautilus'
      get 'tegula'
      get 'unilever'
      get 'wellnessfit'
      get 'nesporte'
      get 'clinicasaraiva'
      get 'putzmeister'
      get 'ceusystem'
      get 'giotto'   
    end
  end
  
  root :to => "homenew#index"
  match 'cadastro' => "users#new"
  match 'login' => 'user_sessions#new'  
  match 'logout' => 'user_sessions#destroy'  

end

app/models/contact.rb
class Contact < ActiveRecord::Base
  attr_accessible :name, :phone, :email, :message
  
  validates_presence_of :name, :message=> " - preencha o campo!"
  validates_presence_of :phone, :message=> " - preencha o campo!"
  validates_presence_of :email, :message=> " - preencha o campo!"
  validates_presence_of :message, :message=> " - preencha o campo!"  
end

app/controllers/admin/contacts_controller.rb
class Admin::ContactsController < ApplicationController
  def index
    @contacts = Contact.all
  end

  def show
    @contact = Contact.find(params[:id])
  end

  def new
    @contact = Contact.new
  end

  def create
    @contact = Contact.new(params[:contact])
    if @contact.save
      redirect_to [:admin, @contact], :notice => "Successfully created contact."
    else
      render :action => 'new'
    end
  end

  def edit
    @contact = Contact.find(params[:id])
  end

  def update
    @contact = Contact.find(params[:id])
    if @contact.update_attributes(params[:contact])
      redirect_to [:admin, @contact], :notice  => "Successfully updated contact."
    else
      render :action => 'edit'
    end
  end

  def destroy
    @contact = Contact.find(params[:id])
    @contact.destroy
    redirect_to admin_contacts_url, :notice => "Successfully destroyed contact."
  end
end

app/controllers/contacts_controller.rb
class ContactsController < ApplicationController
  before_filter :navegadorie6  
  layout "blank" 
  def index
    @contact = Contact.new
  end

  def create
    @contact = Contact.new(params[:contact])
    if !@contact.save
      @erro = true
      @contact.errors
    else
      @erro = false
      UserMailer.send_contact(@contact).deliver
    end
  end
end

app/helpers/admin/contacts_helper.rb
module Admin::ContactsHelper
end

app/helpers/contacts_helper.rb
module ContactsHelper
end

app/views/admin/contacts/_form.html.erb
<%= form_for [:admin, @contact] do |f| %>
  <%= f.error_messages %>
  <p>
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </p>
  <p>
    <%= f.label :phone %><br />
    <%= f.text_field :phone %>
  </p>
  <p>
    <%= f.label :email %><br />
    <%= f.text_field :email %>
  </p>
  <p>
    <%= f.label :message %><br />
    <%= f.text_area :message %>
  </p>
  <p><%= f.submit %></p>
<% end %>

app/views/admin/contacts/edit.html.erb
<% title "Edit Admin/Contact" %>

<%= render 'form' %>

<p>
  <%= link_to "Show", [:admin, @contact] %> |
  <%= link_to "View All", admin_contacts_path %>
</p>

app/views/admin/contacts/index.html.erb
<% title "Admin/Contacts" %>

<table>
  <tr>
    <th>Name</th>
    <th>Phone</th>
    <th>Email</th>
    <th>Message</th>
  </tr>
  <% for contact in @contacts %>
    <tr>
      <td><%= contact.name %></td>
      <td><%= contact.phone %></td>
      <td><%= contact.email %></td>
      <td><%= contact.message %></td>
      <td><%= link_to "Show", [:admin, contact] %></td>
      <td><%= link_to "Edit", edit_admin_contact_path(contact) %></td>
      <td><%= link_to "Destroy", [:admin, contact], :confirm => 'Are you sure?', :method => :delete %></td>
    </tr>
  <% end %>
</table>

<p><%= link_to "New Admin/Contact", new_admin_contact_path %></p>

app/views/admin/contacts/new.html.erb
<% title "New Admin/Contact" %>

<%= render 'form' %>

<p><%= link_to "Back to List", admin_contacts_path %></p>

app/views/admin/contacts/show.html.erb
<% title "Admin/Contact" %>

<p>
  <strong>Name:</strong>
  <%= @contact.name %>
</p>
<p>
  <strong>Phone:</strong>
  <%= @contact.phone %>
</p>
<p>
  <strong>Email:</strong>
  <%= @contact.email %>
</p>
<p>
  <strong>Message:</strong>
  <%= @contact.message %>
</p>

<p>
  <%= link_to "Edit", edit_admin_contact_path(@contact) %> |
  <%= link_to "Destroy", [:admin, @contact], :confirm => 'Are you sure?', :method => :delete %> |
  <%= link_to "View All", admin_contacts_path %>
</p>