config/routes.rb
KwAdministrador::Application.routes.draw do

  resources :user_sessions
  resources :users
  resources :password_resets
  resources :atualizar
  resources :contacts
  namespace(:admin){
    resources :contacts
    resources :static_contents
    resources :users do
      collection do
        get 'search'
      end
    end
    
    root :to => "static_contents#index"
  }
  
  resources :homenew
  resources :portfolio do
    collection do
      get 'adriane'
      get 'aquaclor'
      get 'castelatto'
      get 'fasterm'
      get 'ffa'
      get 'nautilus'
      get 'tegula'
      get 'unilever'
      get 'wellnessfit'
      get 'nesporte'
      get 'clinicasaraiva'
      get 'putzmeister'
      get 'ceusystem'
      get 'giotto'   
    end
  end
  
  root :to => "homenew#index"
  match 'cadastro' => "users#new"
  match 'login' => 'user_sessions#new'  
  match 'logout' => 'user_sessions#destroy'  

end

app/models/user.rb
class User < ActiveRecord::Base
  acts_as_authentic do |c|
    c.login_field = 'email'
  end
  
  acts_as_authorization_subject
  
  scoped_search :on => [:name, :last_name, :email]
  
  validates_presence_of :name, :message=> " - preencha o campo!"
  validates_presence_of :last_name, :message=> " - preencha o campo!"
  validates_presence_of :email, :message=> " - preencha o campo!"
  
  attr_writer :role
  after_save :define_role

  def role
    @role
    if self.has_role? :admin
      @role = :admin
    elsif self.has_role? :supervisor
      @role = :supervisor
    elsif self.has_role? :user
      @role = :user
    end
  end

  def define_role
    if @role
      self.has_no_roles!
      self.has_role! @role
    end
  end

  def deliver_password_reset_instructions!
    reset_perishable_token!
  end
end

app/controllers/admin/users_controller.rb
class Admin::UsersController < ApplicationController
  layout "inadmin"
  
  def index
    @users = User.all.paginate :page => params[:page],:per_page => 20
  end

  def show
    @user = User.find(params[:id])
  end
  
  
  def edit
    @user = User.find(params[:id])
  end

  def update
    @user = User.find(params[:id])
    if @user.update_attributes(params[:user])
      redirect_to admin_user_path(@user), :notice  => "Dados Atualizados com sucesso!"
    else
      render :action => 'edit'
    end
  end
  
  def destroy
    @user = User.find(params[:id])
    @user.destroy
    redirect_to admin_users_path, :notice => "Usuário Deletado com sucesso!"
  end
  
  def search
    if !params[:keyword].blank?
      @Results = User.search_for(params[:keyword]).paginate :page => params[:page],:per_page => 20
    end
  end
    
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_filter :navegadorie6
  layout "admin"
  def new
    @user = User.new
  end

  def create
    @user = User.new(params[:user])
    @user.role = "user"    
    if !@user.save
      @user.errors
    end
  end

  def edit
    @user = current_user
  end

  def update
    @user = current_user
    if @user.update_attributes(params[:user])
      redirect_to home_index_path, :notice  => "Dados Atualizados com sucesso!"
    else
      render :action => 'edit'
    end
  end

end

app/helpers/admin/users_helper.rb
module Admin::UsersHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/admin/users/_form.html.erb
    <div id="Box_register_form">	
		<%= form_for [:admin, @user] do |f| %>
		<div class="field">
			<%= f.label :name, "Nome" %>
			<%= f.text_field :name %>
		</div>
		<div class="field">
			<%= f.label :last_name, "Sobrenome" %>
			<%= f.text_field :last_name %>
		</div>
		<div class="field">
			<%= f.label :email, "E-mail" %>
			<%= f.text_field :email %>
		</div>
		<div class="field">
			<%= f.label :password, "Senha" %>
			<%= f.text_field :password %>
		</div>
		<div id="Box_register_form_regras">
		  <h1>Regras</h1><br />
		  <p>
			Tipo:<br />
			<%= f.radio_button :role, :admin%>Administrador<br/>
			<%= f.radio_button :role, :supervisor %>Supervisor<br/>
			<%= f.radio_button :role, :user %>Usuário<br/>
		  </p><br />
		</div>
  		<p><%= f.submit "Atualizar", :class => "Bt_enviar" %></p>
		<%end%>
	</div>

app/views/admin/users/edit.html.erb
<% 
	content_for :title do "Editar Usuário" end
%>
<%content_for :head do%>
	<%=stylesheet_link_tag "cadastro"%>
	<%= stylesheet_link_tag "admin_user"%>
<%end%>
<div id="Content">
    <div id="Register_internal">
      <p>
		
      </p>
	  <%= render 'form' %>
	</div>
</div>

app/views/admin/users/index.html.erb
<% 
	content_for :title do "Usuários" end
%>
<div id="search">
<p>Informe o nome, sobrenome ou e-mail do usuário.</p>
<%=form_tag '/admin/users/search', :method => :get, :name=>"formkeyword"%>
	<%=text_field_tag :keyword, nil ,:style => "width:400px;"%>
	<%=submit_tag "Buscar", :class => "Bt_enviar"%>
</form>
<br><br>
</div>

<table>
  <tr>
    <th width="200px">Nome</th>
    <th width="200px">Sobrenome</th>
	<th width="200px">Email</th>
  </tr>
  <% for user in @users %>
    <tr>
      <td><%= user.name %></td>
      <td><%= user.last_name %></td>
      <td><%= user.email%></td>
      <td><%= link_to "Show", admin_user_path(user) %></td>
      <td><%= link_to "Edit", edit_admin_user_path(user) %></td>
      <td><%= link_to "Destroy", admin_user_path(user), :confirm => 'Are you sure?', :method => :delete %></td>
    </tr>
  <% end %>
</table>
<%= will_paginate @users %>

<script>
	document.getElementById('keyword').focus();
</script>

app/views/admin/users/new.html.erb
<%content_for :head do%>
	<%=stylesheet_link_tag "cadastro"%>
<%end%>
<% title "Cadastro" %>
<div id="Content">
    <div id="Register_internal">
      <h1>
      	CADASTRAR USÁRIO
      </h1>
      <p>
		
      </p>
	  <%= render 'form' %>
	</div>
</div>

app/views/admin/users/search.html.erb
<% 
	content_for :title do "Resultado da Busca por: #{params[:keyword]}" end
%>
<table>
  <tr>
    <th width="200px">Nome</th>
    <th width="200px">Sobrenome</th>
	<th width="200px">Email</th>
  </tr>
  	<%@Results.each do |user| %>
    <tr>
      <td><%= user.name %></td>
      <td><%= user.last_name %></td>
      <td><%= user.email%></td>
      <td><%= link_to "Show", admin_user_path(user) %></td>
      <td><%= link_to "Edit", edit_admin_user_path(user) %></td>
      <td><%= link_to "Destroy", admin_user_path(user), :confirm => 'Are you sure?', :method => :delete %></td>
    </tr>
  <% end %>
</table>
<br><br>
<%=link_to "Voltar", admin_users_path%>

app/views/admin/users/show.html.erb
<% 
	content_for :title do "Dados do Usuario" end
%>

<p>
  <strong>Nome:</strong>
  <%= @user.name %>
</p>
<p>
  <strong>Sobrenome:</strong>
  <%= @user.last_name %>
</p>
<p>
  <strong>E-mail:</strong>
  <%= @user.email %>
</p>
<p>
  <%= link_to "Edit", edit_admin_user_path(@user) %> |
  <%= link_to "Destroy", admin_user_path(@user), :confirm => 'Are you sure?', :method => :delete %> |
  <%= link_to "View All", admin_users_path %>
</p>