config/routes.rb
KwAdministrador::Application.routes.draw do

  resources :user_sessions
  resources :users
  resources :password_resets
  resources :atualizar
  resources :contacts
  namespace(:admin){
    resources :contacts
    resources :static_contents
    resources :users do
      collection do
        get 'search'
      end
    end
    
    root :to => "static_contents#index"
  }
  
  resources :homenew
  resources :portfolio do
    collection do
      get 'adriane'
      get 'aquaclor'
      get 'castelatto'
      get 'fasterm'
      get 'ffa'
      get 'nautilus'
      get 'tegula'
      get 'unilever'
      get 'wellnessfit'
      get 'nesporte'
      get 'clinicasaraiva'
      get 'putzmeister'
      get 'ceusystem'
      get 'giotto'   
    end
  end
  
  root :to => "homenew#index"
  match 'cadastro' => "users#new"
  match 'login' => 'user_sessions#new'  
  match 'logout' => 'user_sessions#destroy'  

end

app/models/contact.rb
class Contact < ActiveRecord::Base
  attr_accessible :name, :phone, :email, :message
  
  validates_presence_of :name, :message=> " - preencha o campo!"
  validates_presence_of :phone, :message=> " - preencha o campo!"
  validates_presence_of :email, :message=> " - preencha o campo!"
  validates_presence_of :message, :message=> " - preencha o campo!"  
end

app/models/role.rb
class Role < ActiveRecord::Base
  acts_as_authorization_role
end

app/models/user.rb
class User < ActiveRecord::Base
  acts_as_authentic do |c|
    c.login_field = 'email'
  end
  
  acts_as_authorization_subject
  
  scoped_search :on => [:name, :last_name, :email]
  
  validates_presence_of :name, :message=> " - preencha o campo!"
  validates_presence_of :last_name, :message=> " - preencha o campo!"
  validates_presence_of :email, :message=> " - preencha o campo!"
  
  attr_writer :role
  after_save :define_role

  def role
    @role
    if self.has_role? :admin
      @role = :admin
    elsif self.has_role? :supervisor
      @role = :supervisor
    elsif self.has_role? :user
      @role = :user
    end
  end

  def define_role
    if @role
      self.has_no_roles!
      self.has_role! @role
    end
  end

  def deliver_password_reset_instructions!
    reset_perishable_token!
  end
end

app/models/user_session.rb
class UserSession < Authlogic::Session::Base
  
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  helper :all
  protect_from_forgery
  
  helper_method :current_user
  
  def navegadorie6
    if browser.ie6?
      redirect_to atualizar_index_path
    end 
  end
     
  private
  
  def current_user_session
   return @current_user_session if defined?(@current_user_session)
   @current_user_session = UserSession.find
   end

   def current_user
   return @current_user if defined?(@current_user)
   @current_user = current_user_session && current_user_session.record
   end
   
   rescue_from 'Acl9::AccessDenied', :with => :access_denied
   
   def access_denied
     if current_user
       flash[:temerro] = " "
       flash[:error] = 'Você não tem permissão para acessar está página!'
       redirect_to login_path       
     else
       flash[:temerro] = " "
       flash[:error] = 'Acesso negado. Você precisa estar logado.'
       redirect_to login_path
     end
   end
end

app/controllers/atualizar_controller.rb
class AtualizarController < ApplicationController
  layout "atualizar"  
  def index
    
  end
end

app/controllers/contacts_controller.rb
class ContactsController < ApplicationController
  before_filter :navegadorie6  
  layout "blank" 
  def index
    @contact = Contact.new
  end

  def create
    @contact = Contact.new(params[:contact])
    if !@contact.save
      @erro = true
      @contact.errors
    else
      @erro = false
      UserMailer.send_contact(@contact).deliver
    end
  end
end

app/controllers/homenew_controller.rb
class HomenewController < ApplicationController
  #before_filter :navegadorie6
  
  def index
    @menu = true
    
    #FORMULARIO
    @contact = Contact.new
  end
end

app/controllers/password_resets_controller.rb
class PasswordResetsController < ApplicationController
  before_filter :navegadorie6
  layout "admin", :except => [:new, :create]
  def new
  
  end
  
	def create
		@user = User.find_by_email(params[:email])
		if @user && @user.deliver_password_reset_instructions!
			UserMailer.send_email_password_reset(@user).deliver
			@sucess = true
			flash[:error] = "Foi enviado por e-mail a instrução de como alterar a sua senha."
		else
		  @sucess = false
			flash[:error] = "O e-mail digitado é invalido! Digite um e-mail válido."
		end
	end
	

	def edit
	  load_user_using_perishable_token
	  if !@user
	    @sucess = false
	    flash[:temerro] = " "
			flash[:error] = "O link expirou! Tente novamente."
			redirect_to login_path
		end
	end

	def update
	  load_user_using_perishable_token
	  if !@user
	      flash[:error] = "Ocorreu um erro!Tente novamente!"
  			render :action => :edit
	  else
    		@user.password = params[:user][:password]
    		@user.password_confirmation = params[:user][:password_confirmation]
    		if (@user.password != @user.password_confirmation)
    		  @sucess = false
    		  flash[:error_senha] = "Senha e Confirmação de Senha são diferente!"
    		  render :action => :edit
    		else
          if @user.save
            flash[:error] = "Senha alterada com sucesso!"
	          redirect_to login_path
          else
            @sucess = false
            flash[:temerro] = " "
            flash[:error] = "Ocorreu um erro tente novamente!"
	          redirect_to login_path
          end
    	  end
    end
	end

	private
	def load_user_using_perishable_token
		@user = User.find_using_perishable_token(params[:id], 3.hours.to_i)
	end
	
  
end

app/controllers/portfolio_controller.rb
class PortfolioController < ApplicationController
  #before_filter :navegadorie6
  
  def unilever
    redirect_to root_path
  end
end

app/controllers/user_sessions_controller.rb
class UserSessionsController < ApplicationController
  before_filter :navegadorie6
  layout "admin"
  
  def new
    @user_session = UserSession.new
  end
 
  def create
    @user_session = UserSession.new(params[:user_session])
    if @user_session.save
     flash[:error] = "" 
    else
      flash[:error] = "Usuário e/ou senha inválidos!"
    end
  end
 
  def destroy
    @user_session = UserSession.find
    @user_session.destroy
    flash[:notice] = "Sessão finalizada com sucesso."
    redirect_to root_url
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_filter :navegadorie6
  layout "admin"
  def new
    @user = User.new
  end

  def create
    @user = User.new(params[:user])
    @user.role = "user"    
    if !@user.save
      @user.errors
    end
  end

  def edit
    @user = current_user
  end

  def update
    @user = current_user
    if @user.update_attributes(params[:user])
      redirect_to home_index_path, :notice  => "Dados Atualizados com sucesso!"
    else
      render :action => 'edit'
    end
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/atualizar_helper.rb
module AtualizarHelper
end

app/helpers/contacts_helper.rb
module ContactsHelper
end

app/helpers/homenew_helper.rb
module HomenewHelper
end

app/helpers/password_resets_helper.rb
module PasswordResetsHelper
end

app/helpers/portfolio_helper.rb
module PortfolioHelper
end

app/helpers/user_sessions_helper.rb
module UserSessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/_header.html.erb
<div id='logo'>
	<a href="javascript: void(0)" onClick="$('html,body').animate({scrollTop: $('#home').offset().top}, 500);"><img src="/images/logo.png" width="499" height="53" /></a>
</div>
<div id='redes'>
	<a href="javascript: void(0)"><img src="/images/icon_face.jpg" width="30" height="30" /></a>
    <a href="javascript: void(0)"><img src="/images/icon_twitter.jpg" width="30" height="30" /></a>
</div>
<div id='menu'>
	<ul id='ulmenu'>
		<%if @menu == true%>
			<li><a class="home" href="javascript: void(0)">HOME</a></li>
	        <li><a class="agencia" href="javascript: void(0)">AGÊNCIA</a></li>
	        <li><a class="servicos" href="javascript: void(0)">SERVIÇOS</a></li>
	        <li><a class="clientes" href="javascript: void(0)">CLIENTES</a></li>
	        <li><a class="portifolio" href="javascript: void(0)">PORTFÓLIO</a></li>
	        <li><a class="contato" href="javascript: void(0)">CONTATO</a></li>
		<%else%>
			<li><a class="home" href="/?anchor=home">HOME</a></li>
            <li><a class="agencia" href="/?anchor=agencia">AGÊNCIA</a></li>
            <li><a class="servicos" href="/?anchor=servicos">SERVIÇOS</a></li>
            <li><a class="clientes" href="/?anchor=clientes">CLIENTES</a></li>
            <li><a class="portifolio" href="/?anchor=portifolio">PORTFÓLIO</a></li>
            <li><a class="contato" href="/?anchor=contato">CONTATO</a></li>
		<%end%>
    	
    </ul>   
</div>

app/views/layouts/admin.html.erb
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
<title><%= content_for?(:title) ? "Administrador Korewa - " + yield(:title) : "Administrador Korewa" %></title>
<%= stylesheet_link_tag "admin"%>
<%= javascript_include_tag :defaults %>
<script>
jQuery.noConflict();
</script>
<%= javascript_include_tag "menuadmin.js" %>
<%=yield :head%>
</head>
<body>
	<div id="General">
		<div id="Header">
			<div id="User_bar">
				<div id="User_bar_content">
					<%if current_user%>
					<div id="User_name">
						<%= link_to image_tag("img_house.png", :width=>"28", :height=>"23", :class=>"Usr_bt_align"), root_path%><span>Bem Vindo, <%= current_user.name %></span>
					</div>
					<div id="Buttons">
						<%= link_to(image_tag("bt_config.png", :width=>"22", :height=>"22") , edit_user_path(:current), :class => "Usr_bt_align") %>
						<%= link_to(image_tag("bt_ajuda.png", :width=>"22", :height=>"22") , "", :class => "Usr_bt_align") %>
						<%= link_to(image_tag("bt_logout.png", :width=>"22", :height=>"22") , logout_path, :class => "Usr_bt_align") %>
					</div>
					<%end%>
				</div>
			</div>
			<div id="Logo">
				<%= image_tag("logo_default.png", :width=>"148", :height=>"83")%>
			</div>
		</div>
		<div id="Content">
			<div id="Right_box">
				<%=yield%>
			</div>    
			<div class="clear"></div>
			<div id="Footer">
				<div id="Footer_content">
					<p>Kore.Wa CMS © 2011 - all rights reserved.</p> 
					<ul>
						<li><a href="#">Politica de privacidade&nbsp;</a>•&nbsp;</li>
						<li><a href="#">Termos de Uso&nbsp;</a>•&nbsp;</li>
						<li><a href="#">Ajuda&nbsp;</a>•&nbsp;</li>
						<li><a href="#">Suporte </a></li>
					</ul>
					<br />
					<%= link_to(image_tag("logo_korewa.png",:width=>"130",:height=>"54",:alt=>"korewa",:title=>"korewa",:style=>" display:block; float:right; margin-top:70px;"),'http://www.korewa.com.br/')%>
				</div>
			</div>
		</div>
	</div>
</body>
</html>

app/views/layouts/application.html.erb
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />

<%= javascript_include_tag :defaults %>
<%= javascript_include_tag "html5" %>
<%= javascript_include_tag "clientes" %>
<%= javascript_include_tag "portifolio" %>
<%= javascript_include_tag "querystring-0.9.0-min" %>
<%=javascript_include_tag "jquery.validate.min.js"%>
<%=javascript_include_tag "meusmetodos.js"%>
<%=javascript_include_tag "jquery.meio.mask.js"%>
<%=javascript_include_tag "jquery.timers-1.1.2.js"%>
<%=javascript_include_tag "jquery.cycle.all.js"%>
<%=javascript_include_tag "jquery-ui.min.js"%>
<%=javascript_include_tag "sliding_effect.js"%>
<%= stylesheet_link_tag "sliding"%>
<%= stylesheet_link_tag "geral"%>
<%#= stylesheet_link_tag "jquery-ui"%>
<%=yield :head%>
<%= stylesheet_link_tag "reset"%>
<script type="text/javascript">

  var _gaq = _gaq || [];
  _gaq.push(['_setAccount', 'UA-25811568-1']);
  _gaq.push(['_trackPageview']);

  (function() {
    var ga = document.createElement('script'); ga.type = 'text/javascript'; ga.async = true;
    ga.src = ('https:' == document.location.protocol ? 'https://ssl' : 'http://www') + '.google-analytics.com/ga.js';
    var s = document.getElementsByTagName('script')[0]; s.parentNode.insertBefore(ga, s);
  })();

</script>

<script>
function selecionado(obj)
{
	$('#ulmenu > li > a').removeClass('selecionado');
	$(obj).addClass('selecionado');
};

$(document).ready(function(){	
	
	var vai = $.QueryString("anchor"),  
        vai = ( !vai )? "null":vai
		
	if($.QueryString("anchor") != null)
	{
		$('html,body').animate({scrollTop: $("#"+ vai +"").offset().top}, 500);
		selecionado(this);
	}
	
	$('.home').click(function(){
		$('html,body').animate({scrollTop: $('#home').offset().top}, 500);
		selecionado(this);
		});
	
	$('.agencia').click(function(){
		$('html,body').animate({scrollTop: $('#agencia').offset().top}, 500);
		selecionado(this);
		});
		
	$('.servicos').click(function(){
		$('html,body').animate({scrollTop: $('#servicos').offset().top}, 500);
		selecionado(this);
		});
	
	$('.clientes').click(function(){
		$('html,body').animate({scrollTop: $('#clientes').offset().top}, 500);
		selecionado(this);
		});
	
	$('.portifolio').click(function(){
		$('html,body').animate({scrollTop: $('#portifolio').offset().top}, 500);
		selecionado(this);
		});
	
	$('.contato').click(function(){
		$('html,body').animate({scrollTop: $('#contato').offset().top}, 500);
		selecionado(this);
		});
		
	$('.bg1').click(function(){
		$('.img1').fadeIn('slow').removeClass('hide');
		$('.img2').fadeOut('slow').addClass('hide');
		$('.img3').fadeOut('slow').addClass('hide');
		$('.img4').fadeOut('slow').addClass('hide');
		});
	
	$('.bg2').click(function(){
		$('.img2').fadeIn('slow').removeClass('hide');
		$('.img1').fadeOut('slow').addClass('hide');
		$('.img3').fadeOut('slow').addClass('hide');
		$('.img4').fadeOut('slow').addClass('hide');
		});
	
	 $('.bg3').click(function(){
		$('.img3').fadeIn('slow').removeClass('hide');
		$('.img1').fadeOut('slow').addClass('hide');
		$('.img2').fadeOut('slow').addClass('hide');
		$('.img4').fadeOut('slow').addClass('hide');
		});
	
	$('.bg4').click(function(){
		$('.img4').fadeIn('slow').removeClass('hide');
		$('.img1').fadeOut('slow').addClass('hide');
		$('.img2').fadeOut('slow').addClass('hide');
		$('.img3').fadeOut('slow').addClass('hide');
		});
		
	$('#home').cycle({
		fx: 'fade', // choose your transition type, ex: fade, scrollUp, shuffle, etc...
		pager:  '#nav' 
	});
});

function check_text_onfocus(obj)
{
    if(obj.value == obj.defaultValue)
        obj.value = '';
}
function check_text_onblur(obj)
{
    if(obj.value=='')
        obj.value = obj.defaultValue;
}
function insertingmask()
{
	$('input[name="contact[phone]"]').setMask('(99)9999-9999');		
}

function valida(){
	//jQuery("#Box_registration").hide();
	//jQuery("#imgload").show();
	if ($("#new_contact").validate({
        rules: {
            "contact[name]": {
                required: true,
                minlength: 2,
				diferenteDe: "Nome"
            },
			"contact[phone]": {
                required: true,
                minlength: 13,
				diferenteDe: "Telefone"
            },
			"contact[email]": {
                required: true,
                email: true
            },
			"contact[message]":{
				required:true,
				diferenteDe: "Mensagem"
			}

        },
        messages: {
            "contact[name]":{
				required: "*",
				minlength: 	"*"
			},
			"contact[phone]":{
				required: "*",
				minlength: 	"*"
			},
			"contact[email]":{
				required: "*",
				email: "*"	
			},
			"contact[message]":{
				required: "*"	
			}
        }
    }).form()){
		$("#new_contact").submit();
	}else{
		//jQuery("#imgload").hide();
		//jQuery("#Box_registration").show();
	}
}

</script>
<title>SATO7 - Comunicação Estratégica</title>
</head>
<body>
<section>
	<header>
    	<%=render :file => "/layouts/_header.html.erb"%>
    </header>
    
	<%=yield%>
</section>
</body>
</html>

app/views/layouts/atualizar.html.erb
<%= yield %>

app/views/layouts/blank.html.erb
<%= yield %>

app/views/layouts/inadmin.html.erb
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
<title><%= content_for?(:title) ? "Administrador Korewa - " + yield(:title) : "Administrador Korewa" %></title>
<%= stylesheet_link_tag "admin"%>
<%= javascript_include_tag :defaults %>
<script>
jQuery.noConflict();
</script>
<%= javascript_include_tag "menuadmin.js" %>
<%=yield :head%>
</head>
<body>
	<div id="General">
		<div id="Header">
			<div id="User_bar">
				<div id="User_bar_content">
					<div id="User_name">
						<%= link_to image_tag("img_house.png", :width=>"28", :height=>"23", :class=>"Usr_bt_align"), root_path%><span>Bem Vindo, <%= current_user.name %></span>
					</div>
					<div id="Buttons">
						<%= link_to(image_tag("bt_config.png", :width=>"22", :height=>"22") , edit_user_path(:current), :class => "Usr_bt_align") %>
						<%= link_to(image_tag("bt_ajuda.png", :width=>"22", :height=>"22") , "", :class => "Usr_bt_align") %>
						<%= link_to(image_tag("bt_logout.png", :width=>"22", :height=>"22") , logout_path, :class => "Usr_bt_align") %>
					</div>
				</div>
			</div>
			<div id="Logo">
				<%= image_tag("logo_default.png", :width=>"148", :height=>"83")%>
			</div>
		</div>
		<div id="Content">
			<div id="Left_box">
				<div id="Item_category" >
					<h3>Conteúdo</h3><br />
					<!-- 
					<div class="Tab_menu_left">
						<%= link_to image_tag("img_line_up.png", :width=>"220", :height=>"10"),"#"%>
					</div>
					-->
					<div id="Item_content">
						<ul class="Sub_ul">
							<li><%= link_to "Gerenciar Usuários",admin_users_path%></li>
							<!-- 
							<ul>
								<li>subcontent</li>
							</ul>
							<li><a href="#">Artigos</a></li>
							<li><a href="#">Downloads</a></li>
							<li><a href="#">Produtos</a></li>
							<li><a href="#">Fotos</a></li>
							<li><a href="#">Seção</a></li> 
							-->
						</ul>
					</div>
				</div>
			</div>
			<div id="Right_box">
				<%=yield%>
			</div>    
			<div class="clear"></div>
			<div id="Footer">
				<div id="Footer_content">
					<p>Kore.Wa CMS © 2011 - all rights reserved.</p> 
					<ul>
						<li><a href="#">Politica de privacidade&nbsp;</a>•&nbsp;</li>
						<li><a href="#">Termos de Uso&nbsp;</a>•&nbsp;</li>
						<li><a href="#">Ajuda&nbsp;</a>•&nbsp;</li>
						<li><a href="#">Suporte </a></li>
					</ul>
					<br />
					<%= link_to(image_tag("logo_korewa.png",:width=>"130",:height=>"54",:alt=>"korewa",:title=>"korewa",:style=>" display:block; float:right; margin-top:70px;"),'http://www.korewa.com.br/')%>
				</div>
			</div>
		</div>
	</div>
</body>
</html>